name: medicane-env

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xarray
  - netcdf4
  - pyproj
  - cartopy
  - matplotlib
  - h5py
  - geographiclib
  - pip
  - pip:
      - torch==2.13.0
      - torchvision==0.28.0
      - torchmetrics
      - optuna
      - segmentation-models-pytorch
      - python-dotenv